import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <link rel="icon" type="image/png" href="/images/logo/Al_Asmakh_White_For_watermark_gold.png" />
        <title>Mesaimeer City - Al Asmakh Real Estate</title>
    </head>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
